fix cloud reflection and update manifest.json
jebbyk/OSBES-minecraft-bedrock-edition-shader pull request #124
Opened 2021-04-06 07:48 UTC by Mcbamboo

2021-04-07 07:24 UTC, jebbyk commented
yeee, gona check it  (◠﹏◠)

2021-04-07 13:46 UTC, jebbyk requested changes
I've checked it. Seems like water needs some tweaking (maybe only normal map). I'll show a screenshot a bit later.

2021-04-07 14:05 UTC, jebbyk reviewed
![Screenshot_20210407-200433](https://user-images.githubusercontent.com/40975486/113879633-8848be00-97dc-11eb-8adc-ee4a413cc7e3.png)

2021-04-07 14:11 UTC, jebbyk commented
![Screenshot_20210407-200934](https://user-images.githubusercontent.com/40975486/113880395-466c4780-97dd-11eb-9f3e-21d794f4671d.png)
![Screenshot_20210407-200916](https://user-images.githubusercontent.com/40975486/113880436-4cfabf00-97dd-11eb-90cb-3bd3971bc667.png)
horizon color at night should be tuned too

2021-04-07 15:42 UTC, Mcbamboo commented
yes water problem is normalmap and I'll correct the horizon color

2021-04-08 04:42 UTC, jebbyk commented
8x reduced normals strength resulted in this. clouds reflection is much more distorted then the highlight. It is strange. I think there is an issue with vectors calculation somewhere probably even not in the reflection code but in mapping or in specular and diffuse lighting calculations idk.
![Screenshot_20210408-103821](https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png)

2021-04-08 05:04 UTC, Mcbamboo commented
yep,,  because of this

On Thu, Apr 8, 2021 at 11:43 AM Vladimir ***@***.***> wrote:

> 8x reduced normals strength resulted in this. clouds reflection is much
> more distorted then the highlight. It is strange. I think there is an issue
> with vectors calculation somewhere probably even not in the reflection code
> but in mapping or in specular and diffuse lighting calculations idk.
> [image: Screenshot_20210408-103821]
> <https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-815441176>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APGZAH4B4Z7N2FLRIYWLYODTHUX5VANCNFSM42OGDDZQ>
> .
>

2021-04-08 05:07 UTC, Mcbamboo commented
If the reflectedVector is replaced with a normalized relative position it
will be fine and there is no need to reduce the strength of the normalmap

On Thu, Apr 8, 2021 at 12:04 PM sad Kun ***@***.***> wrote:

> yep,,  because of this
>
> On Thu, Apr 8, 2021 at 11:43 AM Vladimir ***@***.***> wrote:
>
>> 8x reduced normals strength resulted in this. clouds reflection is much
>> more distorted then the highlight. It is strange. I think there is an issue
>> with vectors calculation somewhere probably even not in the reflection code
>> but in mapping or in specular and diffuse lighting calculations idk.
>> [image: Screenshot_20210408-103821]
>> <https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png>
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-815441176>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/APGZAH4B4Z7N2FLRIYWLYODTHUX5VANCNFSM42OGDDZQ>
>> .
>>
>

2021-04-08 05:10 UTC, Mcbamboo commented
pos for cloud reflection using reflectedVector which post has normalmap
data and for cloud mounting also use result of dot production from
reflectedVector
well it will make it like in the picture

On Thu, Apr 8, 2021 at 12:06 PM sad Kun ***@***.***> wrote:

> If the reflectedVector is replaced with a normalized relative position it
> will be fine and there is no need to reduce the strength of the normalmap
>
> On Thu, Apr 8, 2021 at 12:04 PM sad Kun ***@***.***> wrote:
>
>> yep,,  because of this
>>
>> On Thu, Apr 8, 2021 at 11:43 AM Vladimir ***@***.***>
>> wrote:
>>
>>> 8x reduced normals strength resulted in this. clouds reflection is much
>>> more distorted then the highlight. It is strange. I think there is an issue
>>> with vectors calculation somewhere probably even not in the reflection code
>>> but in mapping or in specular and diffuse lighting calculations idk.
>>> [image: Screenshot_20210408-103821]
>>> <https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png>
>>>
>>> —
>>> You are receiving this because you authored the thread.
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-815441176>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/APGZAH4B4Z7N2FLRIYWLYODTHUX5VANCNFSM42OGDDZQ>
>>> .
>>>
>>

2021-04-08 05:14 UTC, Mcbamboo commented
sorry I just realized it now

On Thu, Apr 8, 2021, 12:10 PM sad Kun ***@***.***> wrote:

> pos for cloud reflection using reflectedVector which post has normalmap
> data and for cloud mounting also use result of dot production from
> reflectedVector
> well it will make it like in the picture
>
> On Thu, Apr 8, 2021 at 12:06 PM sad Kun ***@***.***> wrote:
>
>> If the reflectedVector is replaced with a normalized relative position it
>> will be fine and there is no need to reduce the strength of the normalmap
>>
>> On Thu, Apr 8, 2021 at 12:04 PM sad Kun ***@***.***> wrote:
>>
>>> yep,,  because of this
>>>
>>> On Thu, Apr 8, 2021 at 11:43 AM Vladimir ***@***.***>
>>> wrote:
>>>
>>>> 8x reduced normals strength resulted in this. clouds reflection is much
>>>> more distorted then the highlight. It is strange. I think there is an issue
>>>> with vectors calculation somewhere probably even not in the reflection code
>>>> but in mapping or in specular and diffuse lighting calculations idk.
>>>> [image: Screenshot_20210408-103821]
>>>> <https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png>
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-815441176>,
>>>> or unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/APGZAH4B4Z7N2FLRIYWLYODTHUX5VANCNFSM42OGDDZQ>
>>>> .
>>>>
>>>

2021-04-08 05:15 UTC, Mcbamboo commented
sorry I just realized it now

On Thu, Apr 8, 2021 at 12:10 PM sad Kun ***@***.***> wrote:

> pos for cloud reflection using reflectedVector which post has normalmap
> data and for cloud mounting also use result of dot production from
> reflectedVector
> well it will make it like in the picture
>
> On Thu, Apr 8, 2021 at 12:06 PM sad Kun ***@***.***> wrote:
>
>> If the reflectedVector is replaced with a normalized relative position it
>> will be fine and there is no need to reduce the strength of the normalmap
>>
>> On Thu, Apr 8, 2021 at 12:04 PM sad Kun ***@***.***> wrote:
>>
>>> yep,,  because of this
>>>
>>> On Thu, Apr 8, 2021 at 11:43 AM Vladimir ***@***.***>
>>> wrote:
>>>
>>>> 8x reduced normals strength resulted in this. clouds reflection is much
>>>> more distorted then the highlight. It is strange. I think there is an issue
>>>> with vectors calculation somewhere probably even not in the reflection code
>>>> but in mapping or in specular and diffuse lighting calculations idk.
>>>> [image: Screenshot_20210408-103821]
>>>> <https://user-images.githubusercontent.com/40975486/113969609-18c3e480-9857-11eb-8962-2d28d4360e31.png>
>>>>
>>>> —
>>>> You are receiving this because you authored the thread.
>>>> Reply to this email directly, view it on GitHub
>>>> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-815441176>,
>>>> or unsubscribe
>>>> <https://github.com/notifications/unsubscribe-auth/APGZAH4B4Z7N2FLRIYWLYODTHUX5VANCNFSM42OGDDZQ>
>>>> .
>>>>
>>>

2021-04-08 06:45 UTC, jebbyk commented
email replies a bit confusing :-D

2021-04-08 15:29 UTC, OpenSauce04 commented
@Mcbamboo Make sure to check how this looks with the new water normals

2021-04-25 05:12 UTC, jebbyk commented on shaders/glsl/includes/reflections.glsl
> +		cldCoord /= cldCoord.y;
I think we can get rid of this cuz probably reflect() already do this job. And also it is probably causing water reflection issue

2021-05-17 03:32 UTC, jebbyk commented
Ive checked some real photos of the water and I think it is everything ok with shader. And I have to reduce normal map strength

2021-05-17 23:05 UTC, Mcbamboo commented
will it work well? sorry I just replied now

On Mon, May 17, 2021, 10:32 AM Vladimir ***@***.***> wrote:

> Ive checked some real photos of the water and I think it is everything ok
> with shader. And I have to reduce normal map strength
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/jebbyk/OSBES-minecraft-bedrock-edition-shader/pull/124#issuecomment-841958140>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APGZAHYVCENU335W2ESQ5R3TOCE5PANCNFSM42OGDDZQ>
> .
>

2021-05-18 04:41 UTC, closed without merging