Added UNDERWATER_EFFECTS toggle to new "effects.glsl" preset file
jebbyk/OSBES-minecraft-bedrock-edition-shader pull request #214
Opened 2021-08-06 19:01 UTC by OpenSauce04

### Summary:
As the title says, I've added a preset toggle that removes underwater effects

Before pulling this, I want to make the toggle not affect the fog or skybox (which I was nearly done with), however my testing setup died on me all of a sudden and won't work again for whatever reason, so this is all I've got for now until that fixes itself ¯\_(ツ)_/¯

2021-08-11 14:12 UTC, OpenSauce04 commented
This PR is now ready for review

2021-08-14 10:45 UTC, OpenSauce04 commented
Don't pull yet, I'm going to seperate the waving effect from the caustics before this is pulled

2021-08-17 03:03 UTC, jebbyk commented
ok

2021-08-23 11:18 UTC, OpenSauce04 commented
@jebbyk This is ready to be checked and pulled

2021-08-27 03:37 UTC, jebbyk requested changes
It is better to place actual distortion calculation in to #if ..... #endif because in this case if UNDERWATER_DISTORTION is not defined  this code will not be even compiled and will not affect performance. Currently even if distortion is disabled this code continues to calculate "distortion" which is equals 0.0.

2021-08-27 07:28 UTC, OpenSauce04 commented
@jebbyk I've tested it and it works absolutely fine, but I can change it

2021-08-30 03:16 UTC, jebbyk commented
@OpenSauce04 Ye Im sure it works, but I'm talking about performance.

2021-08-30 19:20 UTC, OpenSauce04 commented
Ok, I'll work on it now

2021-09-01 04:39 UTC, jebbyk approved these changes

2021-09-01 04:39 UTC, jebbyk commented
I'll check this on my device and merge when have time :-)

2021-10-06 11:59 UTC, jebbyk commented
@OpenSauce04 Hi, can you resolve conflicts?

2021-10-12 14:02 UTC, OpenSauce04 commented
Oh there are conflicts?
Must be due to that other PR, it was fine beforehand
Will fix them

2021-10-21 10:12 UTC, jebbyk commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
I dont think this option is heavy enough to be placed in quality settings

2021-10-21 13:57 UTC, OpenSauce04 commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
What does that even mean?

2021-10-21 13:59 UTC, OpenSauce04 commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
> I dont think this option is heavy enough to be placed in quality settings

What do you mean by that?

2021-10-22 09:58 UTC, jebbyk commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
@OpenSauce04 quality change should affect performance, but this option I think will not affect performance at all. But maybe I'm mistaking

2021-10-22 10:48 UTC, OpenSauce04 commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
It definitely seems like something that would fit into the quality settings, however of you feel strongly enough that it should be moved to preset options, we could do that
I was under the impression that it did affect performance though

2021-10-27 05:18 UTC, jebbyk commented on subpacks/lowest/shaders/glsl/includes/options/quality_settings/effects/underwater_distortion.glsl
> +//#define UNDERWATER_DISTORTION //Comment this line to disable underwater distortion
ok, anyway I'm currently preparing this PR to merge into dev

2021-10-27 10:28 UTC, merged